server:
  port: 8081

spring:
  application:
    name: ebill-service-kg
  datasource:
    kgst:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://3.39.79.144:5432/bestian?currentSchema=kgst&useUnicode=true&characterEncoding=utf8&autoReconnect=true
      username: best
      password: best1234
    homepage:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://43.203.192.251:5432/postgres?currentSchema=homepage&useUnicode=true&characterEncoding=utf8&autoReconnect=true
      username: home
      password: homepass
    asset:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://3.39.79.144:5432/bestian?currentSchema=asset&useUnicode=true&characterEncoding=utf8&autoReconnect=true
      username: best
      password: best1234
#    asset:
#      driver-class-name: org.postgresql.Driver
#      jdbcUrl: jdbc:postgresql://192.168.0.212:5432/bestian?currentSchema=asset_uzb&useUnicode=true&characterEncoding=utf8&autoReconnect=true
#      username: best
#      password: best1234      

#  jta:
#    enabled: true
#    atomikos:
#      datasource:
#        kgst:
#          min-pool-size: 5
#          max-pool-size: 10
#          unique-resource-name: kgstDataSource
#          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
#          xa-properties:
#            user: best
#            password: best1234
#            url: jdbc:postgresql://3.39.79.144:5432/bestian?currentSchema=kgst&useUnicode=true&characterEncoding=utf8&autoReconnect=true
#        homepage:
#          min-pool-size: 5
#          max-pool-size: 10
#          unique-resource-name: homepageDataSource
#          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
#          xa-properties:
#            user: home
#            password: homepass
#            url: jdbc:postgresql://43.203.192.251:5432/postgres?currentSchema=homepage&useUnicode=true&characterEncoding=utf8&autoReconnect=true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: info

#mybatis:
#  mapper-locations: classpath:mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

security:
  allow:
    context-url: http://localhost
    context-url2: http://localhost:5173

jwt:
  secret: 2fdd12003e9607e97e71e0076daea1ec542430ac32a24c16bb322025e36f79d6
  expiration: 86400000
  token-validity-in-seconds: 86400000

edv:
#  rmi: http://localhost:7000/rmi
  #rmi: http://192.168.0.212:7000/rmi
#  rmi: http://3.39.79.144:7000/rmi
  rmi: http://43.203.192.251:7000/rmi
  root-folder: edv
#  property-path: C:/proj/edv_postgre/edv-bestian/repository/datastore/directory.properties
#  property-path: /home/eBill/edv-bestian/repository/datastore/directory.properties
  property-path: /home/EDV/edv-bestian/repository/datastore/directory.properties  
  property-name: subDir
#  datastore-path: C:/proj/edv_postgre/edv-bestian/repository/datastore/${edv.root-folder}
#  datastore-path: /home/eBill/edv-bestian/repository/datastore/${edv.root-folder}
  datastore-path: /home/EDV/edv-bestian/repository/datastore/${edv.root-folder}
  max-use-cpct: 1073741824
  pdf-temp-path: /home/EDV/pdfTmp
  
app:
  sed:
    url: https://testgateway-docs.meria.kg
    access-key: KbrRBpqildJ05XqFEQERV1cHZf
    secret-key: 13a5247a31f4a52b529f8038dc9fb488
  cds:
    url: https://cdsapi-test.srs.kg
    key: d_s9f3htBGUZfaW6gDhgqFX5QCerdnLUIU-5rd4z2EU
    user-agent-org-name: jk
    
scheduler.gateway.new.documents.interval.milliseconds: 300000


file:
  upload:
    path: C:\equipment\
    
    
