spring:
  application:
    name: ebill-service-kg
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.212:5432/bestian?currentSchema=sndb&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: ebsadmin
    password: ebspasswd


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization : true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8081
