server:
  port: 8081

spring:
  application:
    name: ebill-service-kg
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://3.39.79.144:5432/bestian?currentSchema=kgst&useUnicode=true&characterEncoding=utf8&autoReconnect=true
#    username: ebsadmin
#    password: ebspasswd
    username: best
    password: best1234

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: info

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

security:
  allow:
    context-url: http://localhost:3000

edv:
#  rmi: http://localhost:7000/rmi
  #rmi: http://192.168.0.212:7000/rmi
  rmi: http://3.39.79.144:7000/rmi
  root-folder: edv
#  property-path: C:/proj/edv_postgre/edv-bestian/repository/datastore/directory.properties
#  property-path: /home/eBill/edv-bestian/repository/datastore/directory.properties
  property-path: /home/EDV/edv-bestian/repository/datastore/directory.properties  
  property-name: subDir
#  datastore-path: C:/proj/edv_postgre/edv-bestian/repository/datastore/${edv.root-folder}
#  datastore-path: /home/eBill/edv-bestian/repository/datastore/${edv.root-folder}
  datastore-path: /home/EDV/edv-bestian/repository/datastore/${edv.root-folder}